services:
  - type: web
    name: agenticseek-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000