[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_BACKEND_URL = "https://your-backend-url.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://your-backend-url.railway.app"